language: php

php:
  - 5.4

script:
  - phpunit
  - php composer.phar validate

before_script:
  - ./build/bin/install-pecl-libevent.sh
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install